name: CI/CD p

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  prerequisites:
    runs-on: [self-hosted, Linux]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
            
      - name: Install dependencies 
        run: pip3 install pylint 
        
      - name: execute lint script
        run: python3 lint.py >> linted.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: python-script
          path: linted.txt
          
  build:
    runs-on: [self-hosted, Linux]
    needs: [prerequisites]
    steps:
      - name: add lint info
        run: awk '{ print "<p>" $0 "</p>" }' linted.txt > index.html
        
      - name: executed output
        run: python3 main.py | awk '{ print "<p>" $0 "</p>" }' >> index.html
        
      - name: executed output
        run: echo ${{ github.run_id }}
        
          
  deploy:
    runs-on: [self-hosted, Linux]
    needs: [prerequisites, build]
    steps:
    
      - name: docker build
        run: docker build -t devimage:${{ github.run_id }} .
        
      - name: blue/green deploy
        run: docker run -itd -p 9927:8080 -n bluegreendp devimage:${{ github.run_id }}
      
      - name: docker new version simple test
        run: if [[ $(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:9927) -eq '201' ]]; then break; fi
        
      - name: blue/green deploy finish
        run: docker rm -f bluegreendp
        
      - name: 123
        run: docker rm -f prod && docker run -itd -p 8080:8080 -n prod devimage:${{ github.run_id }}

  notification:
    runs-on: [self-hosted, Linux]
    needs: [prerequisites, build, deploy]
    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |  #https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
            Build ${{ github.run_id }} succesfully deployed. Image name devimage:${{ github.run_id }}
            Author:"${{ github.actor }}" triggered by ${{ github.event_name }} in ${{ github.repository }}
        
