name: run main.py

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: weibullguy/python-lint-plus@v1.11.0
      with:
        python-root-list: "tests"
        virtual-env: "python-lint-plus"
        use-docformatter: true
        docformatter-version: "==1.5.0"
        use-isort: true 
        use-pydocstyle: true
        pydocstyle-version: ">=6.1.0"
