name: CI/CD p

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  prerequisites:
    runs-on: [self-hosted, Linux]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
            
      - name: Install dependencies 
        run: pip3 install pylint 
        
      - name: execute py script # run main.py
        run: python3 lint.py >> linted.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: python-script
          path: linted.txt
          
  index:
    runs-on: [self-hosted, Linux]
    needs: [prerequisites]
    steps:
      - name: execute py script # run main.py
        run: echo linted.txt >> index.html
          
  deploy:
    runs-on: [self-hosted, Linux]
    needs: [prerequisites, index]
    steps:
    
      - name: execute py script # run main.py
        run: docker ps
        
