name: CI/CD p

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
            
      - name: Install dependencies 
        run: pip3 install pylint 
        
      - uses: actions/cache@v3
        with:
          path: ../../_tool/Python/3.11.2/x64/lib/python3.11/site-packages  # Note that this path is not influenced by working-directory set in defaults, for example
          key: pip
        
  test:
    runs-on: [self-hosted, Linux]
    needs: [build]
    steps:
    
      - uses: actions/cache@v3
        with:
          path: ../../_tool/Python/3.11.2/x64/lib/python3.11/site-packages  # See the note below
          key: pip  # Must be the same key you specified in the first job

      - name: execute py script # run main.py
        run: python3 lint.py >> linted.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: python-script
          path: linted.txt
          
  deploy:
    runs-on: [self-hosted, Linux]
    needs: [build,test]
    steps:
    
      - name: execute py script # run main.py
        run: docker ps
        
